version: '3'

services:
  kombinatas-radio:
    container_name: kombinatas-radio
    build:
      context: .
      dockerfile: Dockerfile
    expose:
    - '80'
    # ports:
    #   - '8080:80'
    restart: always
    environment:
      VIRTUAL_HOST: kombinatas.online, www.kombinatas.online
      LETSENCRYPT_HOST: kombinatas.online, www.kombinatas.online
      LETSENCRYPT_EMAIL: ignas.an@gmail.com

networks:
  default:
    external:
      name: nginx-proxy